'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import clsx from 'clsx';
import { api, formatDate } from '@/lib/client.js';
import { PageHeader } from '@/components/Shell.jsx';
import { Card, EmptyState, Spinner, StatusBadge, Toast, Button } from '@/components/ui.jsx';
import { Mail, Link2, Copy, ExternalLink } from 'lucide-react';

export default function OutboxView() {
  const [messages, setMessages] = useState(null);
  const [smtp, setSmtp] = useState(false);
  const [selected, setSelected] = useState(null);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    api('/outbox').then((d) => {
      setMessages(d.messages);
      setSmtp(d.smtpConfigured);
      setSelected(d.messages[0] || null);
    }).catch(() => setMessages([]));
  }, []);

  const link = selected ? (selected.text.match(/https?:\/\/\S+\/sign\/\S+/) || [])[0] : null;

  return (
    <>
      <PageHeader
        title="Outbox"
        description={smtp
          ? 'Every message generated by the platform, with its delivery status.'
          : 'No SMTP transport is configured, so messages are captured here instead of being delivered.'}
      />
      <div className="p-5 sm:p-8 max-w-[1400px]">
        {messages === null ? (
          <div className="py-16 flex justify-center text-ink-400"><Spinner size={22} /></div>
        ) : messages.length === 0 ? (
          <Card><EmptyState icon={Mail} title="No messages yet"
            description="Invitations, reminders and completion notices appear here." /></Card>
        ) : (
          <div className="grid lg:grid-cols-[minmax(0,340px)_1fr] gap-5">
            <Card className="overflow-hidden max-h-[70vh] overflow-y-auto">
              <ul className="divide-y divide-ink-200/60">
                {messages.map((m) => (
                  <li key={m.id}>
                    <button onClick={() => setSelected(m)}
                      className={clsx('w-full text-left px-4 py-3 transition-colors',
                        selected?.id === m.id ? 'bg-brand-50/70' : 'hover:bg-ink-50')}>
                      <div className="flex items-center gap-2">
                        <span className="text-[13px] font-medium text-ink-900 truncate flex-1">{m.subject}</span>
                        <StatusBadge status={m.status === 'sent' ? 'completed' : 'declined'} />
                      </div>
                      <p className="mt-0.5 text-[12px] text-ink-500 truncate">{m.to_email}</p>
                      <p className="text-[11px] text-ink-400">{formatDate(m.created_at)} · {m.kind}</p>
                    </button>
                  </li>
                ))}
              </ul>
            </Card>

            {selected && (
              <Card className="overflow-hidden">
                <div className="px-5 py-4 border-b border-ink-200/70">
                  <h2 className="text-[15px] font-semibold text-ink-900">{selected.subject}</h2>
                  <p className="mt-0.5 text-[12.5px] text-ink-500">
                    To {selected.to_name ? `${selected.to_name} <${selected.to_email}>` : selected.to_email} · {formatDate(selected.created_at)}
                  </p>
                  {selected.envelope_id && (
                    <Link href={`/envelopes/${selected.envelope_id}`}
                      className="mt-1.5 inline-flex items-center gap-1 text-[12.5px] text-brand-600 hover:text-brand-700">
                      Open envelope <ExternalLink size={12} />
                    </Link>
                  )}
                </div>
                {link && (
                  <div className="px-5 py-3 border-b border-ink-200/70 bg-ink-50/60">
                    <p className="text-[11.5px] font-medium uppercase tracking-wide text-ink-500 mb-1.5">Signing link</p>
                    <div className="flex items-center gap-2">
                      <Link2 size={14} className="text-ink-400 shrink-0" />
                      <a href={link} target="_blank" rel="noreferrer"
                        className="text-[12px] font-mono text-brand-700 hover:underline truncate">{link}</a>
                      <Button size="sm" variant="secondary" className="ml-auto shrink-0"
                        onClick={() => { navigator.clipboard.writeText(link); setToast({ message: 'Link copied' }); }}>
                        <Copy size={13} /> Copy
                      </Button>
                    </div>
                  </div>
                )}
                <div className="bg-ink-100 p-4">
                  <iframe title="Email preview" srcDoc={selected.html} sandbox=""
                    className="w-full h-[520px] bg-white rounded-lg border border-ink-200" />
                </div>
              </Card>
            )}
          </div>
        )}
      </div>
      <Toast toast={toast} onDismiss={() => setToast(null)} />
    </>
  );
}
